### ISSUE TITLE
Target es5 instead of es6 in tsconfig

### ISSUE THREAD

**Issue by alexbeckwith** [redux-enterprise/redux-enterprise#23]
In order to build with create react app, modules need to compile down to es5.

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

Is there any reason this wouldn't be ok to change?

**Comment by alexfreska** [comment]
@alexbeckwith I just published v0.0.9 to NPM, please let me know if this fixes your issue.

Release Notes
https://github.com/redux-enterprise/redux-enterprise/releases/tag/0.0.9
NPM
https://www.npmjs.com/package/redux-enterprise/v/0.0.9

**Comment by alexfreska** [comment]
@alexbeckwith awesome! Closing this issue.

Also if you hit any limitations in the future, im always open to feedback on the Definitions and ideas for new ones!
